name: waiting_print_proxy
description: A Flutter application to execute local print proxy for waiting system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  
  # Network Utils
  network_info_plus: ^5.0.1
  
  # Background & Wake Lock (Keep screen on)
  wakelock_plus: ^1.1.4
  
  # JSON
  json_annotation: ^4.8.1

  # Database & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # FTP
  ftpconnect: ^2.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
